version: '3.4'
services:
  db:
    image: mirandati7/postgres-spring-boot-softplan
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: softplan
    ports:
      - "5462:5432"
    networks:
      - mr7-network
  spring-boot-softplan:
    image: mirandati7/spring-boot-softplan
    restart: always
    build: ./spring_softplan
    working_dir: /spring_softplan
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./spring_softplan:/spring_softplan
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - mr7-network
networks:
    mr7-network:
        driver: bridge
